#[[main]]
#  name = "About Me"
#  pageRef = "posts"
#  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 20

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[footer]]
  name = "ğŸ“š Series"
  pageRef = "Series"
  weight = 10

[[footer]]
  name = "ğŸ·ï¸ Topics"
  pageRef = "topics"
  weight = 20